export const LOAD_BULK = 'POSTS/LOAD_BULK';
export const LOAD_ONE = 'POSTS/LOAD_ONE';
export const SELECT_CATEGORY_ID_FOR_LIST = 'POSTS/SELECT_CATEGORY_ID_FOR_LIST';
export const SELECT_TAG_ID_FOR_LIST = 'POSTS/SELECT_TAG_ID_FOR_LIST';
