export const INITIALIZE = 'EDITING_POST/INITIALIZE';
export const UPDATE_TITLE = 'EDITING_POST/UPDATE_TITLE';
export const UPDATE_CONTENT = 'EDITING_POST/UPDATE_CONTENT';
export const UPDATE_STATUS = 'EDITING_POST/UPDATE_STATUS';
export const UPDATE_CATEGORIES = 'EDITING_POST/UPDATE_CATEGORIES';
export const UPDATE_TAGS = 'EDITING_POST/UPDATE_TAGS';
