export const INTIALIZE = 'EDITING_POST/INTIALIZE';
export const UPDATE_ARTICLE = 'EDITING_POST/UPDATE_ARTICILE';
export const UPDATE_CATEGORIES = 'EDITING_POST/UPDATE_CATEGORIES';
export const UPDATE_TAGS = 'EDITING_POST/UPDATE_TAGS';
export const UPDATE_POST_STATE = 'EDITING_POST/UPDATE_POST_STATE';
