export const INTIALIZE = 'EDITING_POST/INTIALIZE';
export const UPDATE_CONTENT = 'EDITING_POST/UPDATE_CONTENT';
export const UPDATE_STATUS = 'EDITING_POST/UPDATE_STATUS';
export const UPDATE_CATEGORIES = 'EDITING_POST/UPDATE_CATEGORIES';
export const UPDATE_TAGS = 'EDITING_POST/UPDATE_TAGS';
