export const LOAD_CONFIG = 'CONFIG/LOAD_CONFIG';
export const UPDATE_BLOG_NAME = 'CONFIG/UPDATE_BLOG_NAME';
export const UPDATE_AUTHOR_NAME = 'CONFIG/UPDATE_AUTHOR_NAME';
export const UPDATE_ABOUT_PAGE = 'CONFIG/UPDATE_ABOUT_PAGE';
