const terms = {
  categoryCollectionLabel: 'Category',
  tagCollectionLabel: 'Tags Cloud',
  subscribeLabel: 'Subscribe',
  newPostLabel: 'NEW POST',
  settingLabel: 'SETTING',
  signInLabel: 'SIGN IN',
  signUpLabel: 'SIGN UP',
  signOutLabel: 'SIGN OUT',
  homeLabel: 'HOME',
  archiveLabel: 'ARCHIVE',
  aboutLabel: 'ABOUT',
  newerLabel: 'NEWER',
  olderLabel: 'OLDER',
  postUpdateTimeLabel: 'Update Time',
  viewCountLabel: 'Views',
  commentCountLabel: 'Comments',
  readLabel: 'READ',
  shareLabel: 'SHARE',
  editLabel: 'EDIT',
  writeLabel: 'WRITE',
  previewLabel: 'PREVIEW',
  draftStateLabel: 'Draft',
  publishStateLabel: 'Publish',
  addLabel: 'ADD',
  deleteLabel: 'DELETE',
  saveLabel: 'SAVE IT',
  publishLabel: 'PUBLISH IT',
  setCategoriesLabel: 'SET CATEGORIES FOR POST',
  setTagsLabel: 'Set a tag...',
  initializationTitle: 'Initialize Your Blog',
  blogSettingTitle: 'Blog Setting',
  createAdminAccountTitle: 'Create the Administrator Account',
  loginTitle: 'Login',
  blogNameLabel: 'BLOG NAME',
  authorNameLabel: 'AUTHOR NAME',
  usernameLabel: 'USERNAME',
  mailLabel: 'MAIL',
  passwordLabel: 'PASSWORD',
  confirmPasswordLabel: 'CONFIRM PASSWORD',
  submitCreatingAccountLabel: 'CREATE IT',
  rememberMeLabel: 'Remember me',
  blogNameValidation: 'A Blog Name is necessary.',
  nameValidation: 'Input name is invalid.',
  emailValidation: 'Input E-Mail is invalid.',
  passwordValidation: 'Password contains invalid characters.',
  confirmPasswordValidation: 'Not the same password.'
};

export default terms;
