const terms = {
  categoryCollectionLabel: 'Category',
  tagCollectionLabel: 'Tags Cloud',
  subscribeLabel: 'Subscribe',
  newPostLabel: 'NEW POST',
  configLabel: 'CONFIG',
  signInLabel: 'SIGN IN',
  signUpLabel: 'SIGN UP',
  signOutLabel: 'SIGN OUT',
  homeLabel: 'HOME',
  archiveLabel: 'ARCHIVE',
  aboutLabel: 'ABOUT',
  newerLabel: 'NEWER',
  olderLabel: 'OLDER',
  postUpdateTimeLabel: 'Update Time',
  viewCountLabel: 'Views',
  commentCountLabel: 'Comments',
  readLabel: 'READ',
  shareLabel: 'SHARE',
  editLabel: 'EDIT',
  writeLabel: 'WRITE',
  previewLabel: 'PREVIEW',
  draftStateLabel: 'Draft',
  publishStateLabel: 'Publish',
  addLabel: 'ADD',
  deleteLabel: 'DELETE',
  saveLabel: 'SAVE IT',
  publishLabel: 'PUBLISH IT',
  setCategoriesLabel: 'SET CATEGORIES',
  setTagsLabel: 'Set a tag...'
};

export default terms;
