const terms = {
  title: {
    initialization: 'Initialize Your Blog',
    login: 'Login',
    setting: 'Setting',
    accountSetting: 'Account Setting',
    blogSetting: 'Blog Setting',
    createAdminAccount: 'Create the Administrator Account',
    categoryCollection: 'Category',
    tagCollection: 'Tags Cloud'
  },
  label: {
    subscribe: 'Subscribe',
    newPost: 'NEW POST',
    setting: 'SETTING',
    signIn: 'SIGN IN',
    signUp: 'SIGN UP',
    signOut: 'SIGN OUT',
    home: 'HOME',
    archive: 'ARCHIVE',
    drafts: 'DRAFTS',
    about: 'ABOUT',
    newer: 'NEWER',
    older: 'OLDER',
    postUpdateTime: 'Update Time',
    viewCount: 'Views',
    commentCount: 'Comments',
    read: 'READ',
    share: 'SHARE',
    edit: 'EDIT',
    write: 'WRITE',
    preview: 'PREVIEW',
    draftStatus: 'Draft',
    publishStatus: 'Publish',
    add: 'ADD',
    delete: 'DELETE',
    save: 'SAVE IT',
    publish: 'PUBLISH IT',
    setCategories: 'SET CATEGORIES FOR POST',
    setTags: 'Set a tag...',
    blogName: 'BLOG NAME',
    authorName: 'AUTHOR NAME',
    username: 'USERNAME',
    mail: 'MAIL',
    password: 'PASSWORD',
    confirmPassword: 'CONFIRM PASSWORD',
    submitCreatingAccount: 'CREATE IT',
    rememberMe: 'Remember me',
    update: 'UPDATE'
  },
  placeholder: {
    setBlogName: 'Set your blog name.',
    setAuthorName: 'Set the author name of this blog.',
    setUsername: 'Set username for the account',
    setEmail: 'Set the E-mail for login.',
    setPassword: 'Set password for the acccount.',
    confirmSetPassword: 'Input the password again for confirming.',
    emailForLogin: 'Email, not username',
    passwordForLogin: 'Input your password.',
    loading: 'Loading...'
  },
  validation: {
    blogName: 'A Blog Name is necessary.',
    name: 'Input name is invalid.',
    email: 'Input E-Mail is invalid.',
    password: 'Password contains invalid characters.',
    confirmPassword: 'Not the same password.'
  }
};

export default terms;
